# Generated by Django 2.1.4 on 2019-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190205_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='education and qualifications'),
        ),
    ]
