# Generated by Django 2.1.4 on 2019-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190207_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellee',
            name='twitter_handle',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
