# Generated by Django 2.1.4 on 2019-02-18 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_counsellee_twitter_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contacted', models.DateField(default=django.utils.timezone.now)),
                ('counsellee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellee')),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellor')),
            ],
        ),
        migrations.AddField(
            model_name='counsellor',
            name='counsellees',
            field=models.ManyToManyField(through='users.Counselling', to='users.Counsellee'),
        ),
    ]
