# Generated by Django 2.1.4 on 2019-02-19 10:06

from django.db import migrations, models
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190218_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='counsellee',
            name='categories',
            field=select2.fields.ManyToManyField(sorted=False, to='users.Category'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='areas_of_specialty',
            field=select2.fields.ManyToManyField(sorted=False, to='users.Category'),
        ),
    ]
