# Generated by Django 2.1.4 on 2019-02-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190219_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellor',
            old_name='areas_of_specialty',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='counsellee',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_photos'),
        ),
    ]
