# Generated by Django 2.1.4 on 2019-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190220_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellee',
            name='categories',
            field=models.ManyToManyField(to='users.Category'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='specialty',
            field=models.ManyToManyField(to='users.Category'),
        ),
    ]
