# Generated by Django 2.1.4 on 2019-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190220_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='counsellee',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='counsellor',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='counsellor',
            old_name='specialty',
            new_name='specialties',
        ),
    ]
