# Generated by Django 2.1.4 on 2019-02-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190224_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_photos'),
        ),
    ]
