# Generated by Django 2.1.4 on 2019-02-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190224_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselling',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
    ]
