# Generated by Django 2.1.4 on 2019-02-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190224_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='education and qualifications'),
        ),
    ]
