# Generated by Django 2.1.4 on 2019-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190304_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_photos', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_photos', verbose_name='Profile Picture'),
        ),
    ]
