# Generated by Django 2.1.4 on 2019-03-14 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_auto_20190314_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, null=True, verbose_name='short description')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('word_count', models.TextField(blank=True, null=True)),
                ('sentiment', models.TextField(null=True, verbose_name='sentiment analysis')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False, null=True)),
                ('counsellee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellee')),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellor')),
            ],
            options={
                'ordering': ['counsellee', '-time'],
            },
        ),
    ]
