# Generated by Django 2.1.4 on 2019-01-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('time', models.DateTimeField()),
                ('fixed', models.BooleanField(default=False, null=True)),
                ('held', models.BooleanField(default=False, null=True)),
                ('remarks', models.TextField(null=True)),
                ('recommendations', models.TextField(null=True)),
                ('counsellee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellee')),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellor')),
            ],
        ),
    ]
