# Generated by Django 2.1.4 on 2019-02-12 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_counsellee_twitter_handle'),
        ('counsellia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.TextField(null=True)),
                ('topic', models.TextField(null=True)),
                ('word_count', models.TextField(null=True)),
                ('sentiment', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('counsellee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellee')),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Counsellor')),
            ],
        ),
    ]
