# Generated by Django 2.1.4 on 2019-02-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0004_auto_20190218_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
