# Generated by Django 2.1.4 on 2019-02-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0005_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-time']},
        ),
    ]
