# Generated by Django 2.1.4 on 2019-02-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0006_auto_20190224_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('first', 'first'), ('follow-up', 'follow-up'), ('final', 'final')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='short_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
