# Generated by Django 2.1.4 on 2019-02-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0007_auto_20190224_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='short_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
