# Generated by Django 2.1.4 on 2019-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0009_auto_20190224_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='short description'),
        ),
    ]
