# Generated by Django 2.1.4 on 2019-02-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0010_auto_20190224_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
