# Generated by Django 2.1.4 on 2019-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellia', '0012_auto_20190304_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='counsellee',
        ),
        migrations.RemoveField(
            model_name='report',
            name='counsellor',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counsellee_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counsellor_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='fix appointment?'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='held',
            field=models.BooleanField(default=False, verbose_name='appointment held?'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='requested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateField(verbose_name='Appointment Date'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
